# Deactivated - never got this working

name: Jersey Mike's

on:
  # schedule:
  # - cron: '0 16 * * *'
  workflow_dispatch:
    inputs:
      should-apply:
        description: "Type 'y' to order."

env:
  NODE_VERSION: '16.x'

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      FIRST_NAME: ${{ secrets.FIRST_NAME }}
      LAST_NAME: ${{ secrets.LAST_NAME }}
      CC_NUMBER: ${{ secrets.CC_NUMBER }}
      CC_EXPIRY: ${{ secrets.CC_EXPIRY }}
      CC_CVC: ${{ secrets.CC_CVC }}
      ADDRESS: ${{ secrets.ADDRESS }}
      ZIP: ${{ secrets.ZIP }}
      EMAIL: ${{ secrets.EMAIL }}
      PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4
    - name: Setup Node ${{ env.NODE_VERSION }} Environment
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install dependencies
      run: npm i
    - name: Perform dry run
      if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.should-apply != 'y' }}
      run: node jersey_mikes.ts
    - name: Order food
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.should-apply == 'y' }}
      run: node jersey_mikes.ts -live
    - uses: actions/upload-artifact@v4
      with:
        path: video/*
